"use client";

import { Search, X } from "lucide-react";
import type { RankingFilters as Filters } from "../lib/ranking-utils";

export function RankingFilters({ filters, clubs, onChange, onClear }: { filters: Filters; clubs: { id: string; name: string }[]; onChange: (key: keyof Filters, value: string) => void; onClear: () => void }) {
  const hasFilters = Object.values(filters).some(Boolean);
  return <div className="rounded-2xl border border-white/10 bg-card/70 p-4"><div className="grid gap-3 md:grid-cols-3 lg:grid-cols-6"><label className="relative md:col-span-2"><span className="sr-only">Buscar atleta, club o competencia</span><Search size={16} className="absolute left-3 top-1/2 -translate-y-1/2 text-muted-foreground" /><input value={filters.search ?? ""} onChange={(event) => onChange("search", event.target.value)} placeholder="Buscar atleta, club o competencia" className="h-10 w-full rounded-lg border border-white/10 bg-secondary pl-9 pr-3 text-sm text-white placeholder:text-muted-foreground focus:border-accent focus:outline-none" /></label><Select label="Categoría" value={filters.category} onChange={(value) => onChange("category", value)} options={["Absoluta", "Junior", "Juvenil"]} /><Select label="Disciplina" value={filters.discipline} onChange={(value) => onChange("discipline", value)} options={["Natación", "Aguas abiertas"]} /><Select label="Estilo" value={filters.stroke} onChange={(value) => onChange("stroke", value)} options={["Libre", "Dorso", "Pecho", "Mariposa", "Aguas abiertas"]} /><Select label="Piscina" value={filters.course} onChange={(value) => onChange("course", value)} options={["SC", "LC", "OW"]} /><Select label="Club" value={filters.club} onChange={(value) => onChange("club", value)} options={clubs.map((club) => club.id)} labels={Object.fromEntries(clubs.map((club) => [club.id, club.name]))} /></div>{hasFilters && <button type="button" onClick={onClear} className="mt-3 inline-flex items-center gap-1 text-xs font-bold uppercase tracking-widest text-accent hover:text-white"><X size={14} /> Limpiar filtros</button>}</div>;
}

function Select({ label, value = "", options, labels = {}, onChange }: { label: string; value?: string; options: string[]; labels?: Record<string, string>; onChange: (value: string) => void }) { return <label><span className="sr-only">Filtrar por {label}</span><select aria-label={label} value={value} onChange={(event) => onChange(event.target.value)} className="h-10 w-full rounded-lg border border-white/10 bg-secondary px-3 text-sm text-white focus:border-accent focus:outline-none"><option value="">{label}</option>{options.filter((option, index) => options.indexOf(option) === index).map((option) => <option key={option} value={option}>{labels[option] ?? option}</option>)}</select></label>; }
