import Link from "next/link";
import { ArrowLeft, CalendarDays, MapPin, ShieldCheck } from "lucide-react";
import { ROUTES } from "@/features/navigation";
import type { Athlete } from "../types/athlete.types";
import { calculateAge } from "../lib/formatters";

export function AthleteProfileHeader({ athlete }: { athlete: Athlete }) {
  return <div className="relative overflow-hidden rounded-2xl border border-white/10 bg-card/80 p-6 sm:p-8"><div className="absolute -right-12 -top-16 h-56 w-56 rounded-full bg-accent/10 blur-3xl" /><Link href={ROUTES.atletasPagina} className="relative inline-flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-accent hover:text-white"><ArrowLeft size={14} /> Volver a atletas</Link><div className="relative mt-8 flex flex-col gap-6 sm:flex-row sm:items-center"><div className="flex h-28 w-28 shrink-0 items-center justify-center rounded-2xl bg-gradient-to-br from-primary to-accent/20 text-4xl font-black text-white ring-4 ring-accent/10" style={{ fontFamily: "'Barlow Condensed', sans-serif" }}>{athlete.firstName[0]}{athlete.lastName[0]}</div><div><div className="flex flex-wrap items-center gap-2 text-xs font-bold uppercase tracking-[0.18em] text-accent"><ShieldCheck size={14} /> Atleta federado · {athlete.federationCode}</div><h1 className="mt-2 text-5xl font-black uppercase leading-none text-white sm:text-6xl" style={{ fontFamily: "'Barlow Condensed', sans-serif" }}>{athlete.firstName} <span className="text-accent">{athlete.lastName}</span></h1><Link href={ROUTES.clubDetalle(athlete.team.id)} className="mt-3 inline-flex text-base text-white/70 hover:text-accent">{athlete.team.name} · {athlete.team.city}</Link><div className="mt-4 flex flex-wrap gap-4 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1.5"><CalendarDays size={14} className="text-accent" /> {calculateAge(athlete.birthDate)} años · {athlete.gender === "F" ? "Femenino" : "Masculino"}</span><span className="inline-flex items-center gap-1.5"><MapPin size={14} className="text-accent" /> {athlete.nationality}</span></div></div></div></div>;
}
