import { CalendarDays, MapPin, Trophy } from "lucide-react";
import type { AthleteCompetition } from "../types/athlete.types";
import { formatDate } from "../lib/formatters";

export function CompetitionHistory({ competitions }: { competitions: AthleteCompetition[] }) {
  return <section><div className="mb-5 flex items-end justify-between gap-3"><div><p className="text-xs uppercase tracking-[0.2em] text-accent">Trayectoria</p><h2 className="mt-1 text-3xl font-black uppercase text-white" style={{ fontFamily: "'Barlow Condensed', sans-serif" }}>Competencias</h2></div><span className="text-xs text-muted-foreground">{competitions.length} registradas</span></div>{competitions.length === 0 ? <EmptyState label="Aún no hay competencias registradas." /> : <div className="space-y-3">{competitions.map((competition) => <div key={competition.id} className="flex flex-col gap-4 rounded-xl border border-white/10 bg-card/60 p-4 sm:flex-row sm:items-center"><div className="flex h-11 w-11 shrink-0 items-center justify-center rounded-lg bg-accent/10 text-accent"><Trophy size={19} /></div><div className="min-w-0 flex-1"><h3 className="font-semibold text-white">{competition.name}</h3><div className="mt-1 flex flex-wrap gap-x-4 gap-y-1 text-xs text-muted-foreground"><span className="inline-flex items-center gap-1"><CalendarDays size={12} /> {formatDate(competition.date)}</span><span className="inline-flex items-center gap-1"><MapPin size={12} /> {competition.location}</span></div></div><div className="flex gap-6 text-left sm:text-right"><div><p className="text-lg font-black text-accent" style={{ fontFamily: "'Barlow Condensed', sans-serif" }}>#{competition.bestPlace}</p><p className="text-[10px] uppercase tracking-wide text-muted-foreground">Mejor lugar</p></div><div><p className="text-lg font-black text-white" style={{ fontFamily: "'Barlow Condensed', sans-serif" }}>{competition.points}</p><p className="text-[10px] uppercase tracking-wide text-muted-foreground">Puntos</p></div></div></div>)}</div>}</section>;
}

function EmptyState({ label }: { label: string }) { return <div className="rounded-xl border border-dashed border-white/15 p-8 text-center text-sm text-muted-foreground">{label}</div>; }
