import Link from "next/link";
import { Medal, Trophy, UsersRound } from "lucide-react";
import { ROUTES } from "@/features/navigation";
import type { Athlete } from "@/features/athletes";
import { getClubStats } from "../lib/club-stats";
import type { Club } from "../types/club.types";

export function ClubDetailSections({ club, athletes }: { club: Club; athletes: Athlete[] }) { const stats = getClubStats(club); return <div className="mt-10 grid gap-8 lg:grid-cols-[1.2fr_0.8fr]"><section><div className="mb-4 flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-accent"><UsersRound size={15} /> Atletas actuales</div><div className="grid gap-3 sm:grid-cols-2">{athletes.map((athlete) => <Link key={athlete.id} href={ROUTES.atletaDetalle(athlete.id)} className="rounded-xl border border-white/10 bg-card/60 p-4 hover:border-accent/40"><p className="text-lg font-black uppercase text-white" style={{ fontFamily: "'Barlow Condensed', sans-serif" }}>{athlete.firstName} {athlete.lastName}</p><p className="mt-1 text-xs text-muted-foreground">{athlete.performances.length} marcas · {athlete.medals.length} medallas</p></Link>)}</div>{athletes.length === 0 && <Empty text="Este club todavía no tiene atletas registrados." />}</section><div className="space-y-8"><section><div className="mb-4 flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-accent"><Trophy size={15} /> Competencias destacadas</div><div className="space-y-3">{club.competitions.map((competition) => <div key={competition.id} className="rounded-xl border border-white/10 bg-card/60 p-4"><p className="font-bold text-white">{competition.name}</p><p className="mt-1 text-xs text-muted-foreground">{competition.date} · Mejor posición {competition.bestPlace} · {competition.points} puntos</p></div>)}</div>{club.competitions.length === 0 && <Empty text="Aún no hay competencias registradas." />}</section><section><div className="mb-4 flex items-center gap-2 text-xs font-bold uppercase tracking-widest text-accent"><Medal size={15} /> Medallero</div><div className="grid grid-cols-3 gap-3"><MedalStat label="Oro" value={stats.goldMedals} color="text-yellow-300" /><MedalStat label="Plata" value={stats.silverMedals} color="text-slate-300" /><MedalStat label="Bronce" value={stats.bronzeMedals} color="text-amber-600" /></div></section></div></div>; }
function MedalStat({ label, value, color }: { label: string; value: number; color: string }) { return <div className="rounded-xl border border-white/10 bg-card/60 p-4 text-center"><p className={`text-3xl font-black ${color}`} style={{ fontFamily: "'Barlow Condensed', sans-serif" }}>{value}</p><p className="text-[10px] uppercase tracking-widest text-muted-foreground">{label}</p></div>; }
function Empty({ text }: { text: string }) { return <div className="rounded-xl border border-dashed border-white/15 p-8 text-center text-sm text-muted-foreground">{text}</div>; }
